server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://staffflow-db:5432/hrms-spring-jpa
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
